### ISSUE TITLE
[New Data] 7-location PMU data from the Nordic Grid, 2013

### ISSUE THREAD

**Issue by LRydin** [LRydin/Power-Grid-Frequency#31]
Adding 7 synchronous recordings from the Nordic Grid from 2013, provided by [Luigi Vanfretti](https://faculty.rpi.edu/node/36204), Professor at RPI and head of @ALSETLab (@lvanfretti), stemming for the discontinued project STRONg²rid. The data are synchronous and over a period of ~3 days.

This needs to be added to:
 - [x] Map
 - [x] Database

and we need to ensure
 - [x] links to the project are detailed
 - [x] links to the authors are detailed
 - [x] licensing and referencing are detailed correctly

M. S. Almas, M. Baudette, L. Vanfretti, S. Løvlund,and J. O. Gjerde, _Synchrophasor network, laboratory and software applications developed in the STRONg2rid project_, in 2014 IEEE PES General Meeting | ConferenceExposition (2014) pp. 1–5.

**Comment by lvanfretti** [comment]
@LRydin thanks for including it in your project and website!

**Comment by LRydin** [comment]
> @LRydin thanks for including it in your project and website!
:)
