### ISSUE TITLE
Incorrect Data

### ISSUE THREAD

**Issue by thesairam** [LRydin/Power-Grid-Frequency#44]
Hi LRydin, I am working on a project and I find your data to be very useful. However, if I see the frequency data, I see weird values like 25, -7 etc and nothing is around 50. 

Am I missing something? Please guide. Thank you.

**Comment by LRydin** [comment]
Hey @thesairam. The data is given with 50 Hz subtracted and in mHz, i.e.,

data = (f - 50)/1000

with f the real frequency in Hz. 
Cheers!

**Comment by thesairam** [comment]
Ah I get it, I think the correct formula should be:

df['Frequency'] = df['Frequency']/1000 + 50
print(df)

Because, the formula you had described would result in huge numbers, for instance, 25 would result in 25050.

Please let me know if my interpretation is correct.

Thank you
Sairam.
________________________________

**Comment by LRydin** [comment]
You are absolutely correct. I wrote the formula this morning from bed, thus the blatant mistake :P. I'll mark this as closed.

Cheers and best of luck with the data! If anything else is needed, feel free to write.
Leo

**Comment by thesairam** [comment]
Thank you!!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
